description: >
  Install and run semantic-release with minimal configuration

executor: default

parameters:
  tag_format:
    default: '${version}'
    description: Tag format (make sure to escape dollar signs)
    type: string
  attach_workspace:
    default: false
    description: >
      Boolean for whether or not to attach to an existing workspace.
    type: boolean
  workspace_root:
    default: .
    description: >
      Workspace root path that is either an absolute path or a path relative to the working directory.
    type: string

steps:
  - checkout
  - when:
      condition: <<parameters.attach_workspace>>
      steps:
        - attach_workspace:
            at: <<parameters.workspace_root>>
  - install
  - create_minimal_config_github:
      tag_format: <<parameters.tag_format>>
  - execute
