description: >
  Install and run semantic-release with existing configuration files

executor: default

parameters:
  additional_packages:
    default: ""
    description: Additional npm packages to install, seperated by space
    type: string
  validate_config_file:
    default: false
    description: Validate the presence of the configuration file in the project
    type: boolean
  config_file:
    default: ".releaserc.json"
    description: Configuration file to check
    type: string
  attach_workspace:
    default: false
    description: >
      Boolean for whether or not to attach to an existing workspace.
    type: boolean
  workspace_root:
    default: .
    description: >
      Workspace root path that is either an absolute path or a path relative to the working directory.
    type: string

steps:
  - checkout
  - when:
      condition: <<parameters.attach_workspace>>
      steps:
        - attach_workspace:
            at: <<parameters.workspace_root>>
  - when:
      condition: <<parameters.validate_config_file>>
      steps:
        - verify_config:
            config_file: <<parameters.config_file>>
  - install:
      additional_packages: <<parameters.additional_packages>>
  - execute
