description: >
  Default executor using node 16.14

docker:
  - image: 'cimg/node:<<parameters.tag>>'

parameters:
  tag:
    default: "16.14"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
